### ISSUE TITLE
Support $meta-add Operation

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#121]
A user will need to be able to update the meta of a resource without changing the version of the document. This will need to be supported so that the customer will be able to participate in access control. 

A facility to support this is available via the $meta-add operation. The details of the implementation can be found here: https://www.hl7.org/fhir/resource-operations.html#2.28.7.3 

**Acceptance Criteria:**
- [ ] Operation adds meta that is supplied that isn't already present
- [ ] Operation does not add duplicates of the meta information that already exists
- [ ] Additional indexes are created as needed on resources
- [ ] Updated meta is returned from the operation
- [ ] Updated meta is returned on the resource when pulled directly

**Comment by CaitlinV39** [comment]
@ginalee-dotcom FYI on a GitHub issue for $meta-add

**Comment by CaitlinV39** [comment]
I'm going to close this issue given that it was opened by the FHIR team and is a feature request. If we see additional requests in the future we can open a new issue.

**Comment by jaime-olivares** [comment]
Hi @CaitlinV39 ,
The Efferent FHIR server supports $meta-add for tagging any FHIR resource in the UI. It is an extremely useful feature because it doesn't require updating the entire resource just for adding a tag.
