### ISSUE TITLE
Support $meta-remove operation

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#122]
A user will need to be able to remove the meta of a resource without changing the version of the document. This will need to be supported so that the customer will be able to participate in access control. 

A facility to support this is available via the $meta-delete operation. The details of the implementation can be found here: https://www.hl7.org/fhir/resource-operations.html#2.28.7.4

**Acceptance Criteria**
- [ ] Operation removes meta that is supplied that is present
- [ ] Operation no-ops for a particular change if it's not present in the meta
- [ ] Indexes are removed as needed on resources
- [ ] Updated meta is returned from the operation
- [ ] Updated meta is returned on the resource when pulled directly

**Comment by CaitlinV39** [comment]
@ginalee-dotcom FYI on $meta-remove

**Comment by CaitlinV39** [comment]
I'm going to close this issue given that it was opened by the FHIR team and is a feature request. If we see additional requests in the future we can open a new issue.
